# Generated by Django 5.2.6 on 2025-09-13 22:40

import branding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Upload site logo (SVG/PNG preferred, max 512KB, max 512×512px)', null=True, upload_to='branding/logos/', validators=[branding.models.validate_logo_file_size, branding.models.validate_image_size])),
                ('logo_alt_text', models.CharField(default='Site Logo', help_text='Alt text for accessibility and SEO', max_length=200)),
                ('logo_max_width', models.PositiveIntegerField(default=200, help_text='Maximum width for logo display (pixels)')),
                ('logo_link_target', models.CharField(default='/', help_text='URL where logo click should navigate', max_length=200)),
                ('favicon', models.ImageField(blank=True, help_text='Upload favicon (ICO/PNG/SVG, max 256KB)', null=True, upload_to='branding/favicons/', validators=[branding.models.validate_favicon_file_size])),
                ('favicon_ico', models.FileField(blank=True, editable=False, null=True, upload_to='branding/favicons/')),
                ('favicon_svg', models.FileField(blank=True, editable=False, null=True, upload_to='branding/favicons/')),
                ('favicon_32', models.ImageField(blank=True, editable=False, null=True, upload_to='branding/favicons/')),
                ('favicon_16', models.ImageField(blank=True, editable=False, null=True, upload_to='branding/favicons/')),
                ('apple_touch_icon', models.ImageField(blank=True, editable=False, null=True, upload_to='branding/favicons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
            },
        ),
    ]
