# Generated by Django 5.2.5 on 2025-09-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_avif',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/extra/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_webp',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/extra/'),
        ),
    ]
