# Generated by Django 5.2.5 on 2025-09-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage_image_avif_productimage_image_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_avif',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_webp',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='products/'),
        ),
    ]
