name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    env:
      DJANGO_SECRET_KEY: dummy
      DEBUG: "0"
      # Ако имаш Stripe ключове/др. – добави ги като GitHub Secrets и ги реферирай тук:
      # STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      # STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      # STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      SITE_URL: http://localhost:8000
      USE_S3: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django checks & migrate (SQLite)
        run: |
          python manage.py check
          python manage.py migrate --noinput
          # по избор: 
          python manage.py collectstatic --noinput

      - name: Run pytest
        run: |
          pytest -q
